### PR TITLE
Add support for custom vivado version

### PR DESCRIPTION
**Pull request by TristanCacqueray**
This change enables using clash-shake with vivado 2018.2.

### CODE REVIEW

**Comment by TristanCacqueray** [comment]
That seems to work with the version I got after reading the digilent documentation. Though perhaps this could be set with a simpler getEnv?

**Comment by gergoerdi** [comment]
Ugh, it would be nice to completely avoid this issue. Is there some minimum Vivado version we could use in the template that would work for everything? I don't know...

As one data point, I just tried locally, and hardcoding the version to 2018 allowed me to synthesize all the way to bitfile on Vivado 2019.1. Could we set it to 2012, the first year Vivado was released? 

Alternatively, since we can run Vivado at any point of the build process, we could try parsing the output of `vivado -version` which for me reports:

```
Vivado v2019.1 (64-bit)
SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
IP Build 2548770 on Fri May 24 18:01:18 MDT 2019
Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
```

So if the first line is always `Vivado v${VERSION} ${ARCH}` we could try parsing that.

**Comment by gergoerdi** [comment]
Could you try with https://github.com/gergoerdi/clash-shake/commit/c05410598438cb5e493395be371083110dfe2dbe and report back if it works for you?

**Comment by TristanCacqueray** [comment]
@gergoerdi thanks for the quick fix, it seems to works with my 2018.2 install.

**Comment by gergoerdi** [comment]
Thank you for reporting back! I have now released `clash-shake` 0.2.1 with this fix.

**Pull request closed without merging**
